### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by moose4lord** [bkpsu/NodeMCU-Breakout-Board#1]
From our previous discussion on thingiverse.com regarding suggestions for a v2.0 breakout board:

1) add prevision for a resistor/diode between D0 and RST (can flash the ESP while mounted on the board).
2) add provision for a capacitor on the 5V supply (better noise suppression).
3) Replace the I2C level shifter with a 74HC245 or 74HC125 buffer chip (better NeoPixel compatibility).

What did I forget? :)

**Comment by moose4lord** [comment]
Another thing I wish the v1.1 breakout board had is compatibility with ESP32. Although there seem to be a few incompatible development boards available for the ESP32 (36 pins), there's one made by DOIT that's pretty similar to the NodeMCU. It shares the same 30-pin form factor and the Vin/GND/3v3 pins at the bottom of the dev board. See [here](https://github.com/SmartArduino/SZDOITWiKi/wiki/ESP8266---ESP32) .

Here's the kicker. The width of this dev board is between the NodeMCU 0.9 and the NodeMCU 1.0. The NodeMCU 0.9 spans all 10 pins of a standard breadboard, the NodeMCU 1.0 is thinner, spanning 8 pins, and the ESP32 spans 9 pins. I was hoping the breakout board could accommodate the ESP32 like this:
```
 |--- NodeMCU 0.9 ---|
 |----- ESP32 ------|
  |-- NodeMCU 1.0 --|
ooo                 ooo row 1
ooo                 ooo row 2
 .                  .
 .                  .
 .                  .
ooo                 ooo row 15
```
But alas, the rows of vias for the NodeMCU 1.0 are offset vertically just a smidge from the vias for the 0.9, so my ESP32 can't use the 0.9 vias on one side and the 1.0 vias on the other. It would be nice if all the vias were aligned.

Maybe it would be easier to arrange the vias like so:
```
 |--- NodeMCU 0.9 ---|
  |----- ESP32 ------|
   |-- NodeMCU 1.0 --|
oooo                 oo row 1
oooo                 oo row 2
  .                  .
  .                  .
  .                  .
oooo                 oo row 15
```

Also, the 3v3 and GND pins in the middle of the NodeMCU dev boards aren't there on the ESP32, so that would have to be dealt with using jumpers or solder blob bridges maybe. Just thinking out loud.

**Comment by bkpsu** [comment]
@moose4lord - thanks for joining in and posting all your suggestions! I'm definitely in favor of all of them, but I have a few caveats/comments:

1. Could you possibly open a new issue for each of your suggestions? I'd like to track/close them as individual items, just to keep in the spirit of Github/issue reporting
2. The reason for the offset between 0.9/1.0 pins is dual:
     a) To allow the 1.0 board to fit in the same enclosure as the 0.9 (the 1.0 board sticks out a few mm more than the 0.9
     b) To prevent pads interfering with each other (even though this wouldn't matter electrically, it might make it harder to solder headers nicely without having overflow)
3. While I like the idea of supporting the ESP32 board, I just think it's too different and pin-incompatible. For example, the 3v3/Gnd pins I use for my I2C OLED screens on the bottom right are now 3v3/CLK pins on the ESP32 board. The A0 analog input on NodeMCU is an "EN" pin on the ESP32, etc...I don't mind creating a new flavor of the breakout board, geared toward the ESP32, and the board you mentioned is definitely one of the better ESP32 devkits I've seen, but I just don't think we can hope to support both the ESP8266 NodeMCU and ESP32 boards in one PCB.

**Comment by bkpsu** [comment]
Added v1.2 files - including the fixes mentioned here - except for cap on the 5V line (still don't have a dedicated power input to this, expecting USB input, which is regulated on the NodeMCU).
